import http from './http'

export const getAdminDashboard = () => http.get('/admin/dashboard')
export const getAdminEmails = () => http.get('/admin/emails')
export const getAdminEmail = fileName => http.get(`/admin/emails/${encodeURIComponent(fileName)}`)
export const getAdminUsers = () => http.get('/admin/users')
export const deleteAdminUser = id => http.delete(`/admin/users/${id}`)
export const getAdminProducts = () => http.get('/admin/products')
export const getAdminProduct = id => http.get(`/admin/products/${id}`)
export const createAdminProduct = payload => http.post('/admin/products', payload)
export const updateAdminProduct = (id, payload) => http.post(`/admin/products/${id}`, payload)
export const deleteAdminProduct = id => http.delete(`/admin/products/${id}`)
export const getAdminOrders = () => http.get('/admin/orders')
export const getAdminOrder = id => http.get(`/admin/orders/${id}`)
export const getAdminOrderItems = id => http.get(`/admin/orders/${id}/items`)
export const updateAdminOrderStatus = (id, status) => http.patch(`/admin/orders/${id}/status`, { status })
export const getAdminAppointments = () => http.get('/admin/appointments')
export const createAdminAppointmentSlot = payload => http.post('/admin/appointments/slots', payload)
export const updateAdminAppointmentStatus = (id, status) => http.patch(`/admin/appointments/${id}/status`, { status })